// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN-_arQLIEL6YMiHpqGKt-XJNYTObZHcM',
    appId: '1:856498453858:web:ec651ef8741c361a9fc03b',
    messagingSenderId: '856498453858',
    projectId: 'ebot-46ad9',
    authDomain: 'ebot-46ad9.firebaseapp.com',
    storageBucket: 'ebot-46ad9.appspot.com',
    measurementId: 'G-4RJ6W2TC5Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrNK75ABqihRn0-1jwMdVtcbUoVHDxpLw',
    appId: '1:856498453858:ios:a9f51bf690cb610f9fc03b',
    messagingSenderId: '856498453858',
    projectId: 'ebot-46ad9',
    storageBucket: 'ebot-46ad9.appspot.com',
    iosClientId: '856498453858-ttl3e0rf5kbkboj6vskjtndfpu2qc6og.apps.googleusercontent.com',
    iosBundleId: 'com.example.bot',
  );
}
